name: DukesMart
main: com.ruinscraft.dukesmart.DukesMart
version: 0.1
author: Ruinscraft LLC
api-version: 1.13
commands:
  shop:
    description: Shows all commands for DukesMart
    usage: /shop
    permission: dukesmart.shop